services:
  web:
    build: .                                                   # Build Docker image from current directory using Dockerfile
    container_name: Your_container_name                        # Assign a custom container name
    command: >                                                 # Override default CMD to run migrations, collect static files, then start server
      sh -c "python manage.py migrate &&                       
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:                                               # Pass environment variables (can be used inside Django settings.py)
      DJANGO_SETTINGS_MODULE: VTRYON.settings                  # Django settings module from .env
      DB_NAME: ${DB_NAME}                                      # Database name from .env
      DB_USER: ${DB_USER}                                      # Database user name from .env
      DB_PASSWORD: ${DB_PASSWORD}                              # Database password from .env
      DB_HOST: your_db_hostname                                # Database host
      DB_PORT: your_db_port                                    # Database port
    ports:                                                     # Map container port 8000 to host port 8000
      - "8000:8000" 
